source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/stanwood/Cocoa_Pods_Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'Stanwood_Dialog_iOS_Example' do
  pod 'StanwoodDialog', :path => '../'

  target 'Stanwood_Dialog_iOS_Tests' do
    inherit! :search_paths

    
  end
end
