source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:stanwood/Cocoa_Pods_Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'Stanwood_Dialog_iOS_Example' do
  pod 'StanwoodDialog', :path => '../'
end

target 'Stanwood_Dialog_iOS_Tests' do
    inherit! :search_paths
    
end
