source 'git@github.com:CocoaPods/Specs.git'

platform :ios, '9.3'
use_frameworks!

target 'Stanwood_Dialog_iOS_Example' do
  pod 'StanwoodAnalytics', git: 'git@github.com:stanwood/Stanwood_Analytics_iOS.git', branch: 'ios9-compatibility'
  pod 'Firebase/Analytics'
  pod 'StanwoodDialog', :path => '../'
end

target 'Stanwood_Dialog_iOS_Tests' do
    inherit! :search_paths
    
end
