output: docs
clean: true
skip_undocumented: true
sdk: iphone
swift_version: 5
module_version: 0.0.42
xcodebuild_arguments: [clean,build,-project,_Pods.xcodeproj,-scheme,StanwoodDialog]
source_directory: StanwoodDialog/Classes
author: Eugene Peschard
author_url: ios@stanwood.io
copyright: 2018 Stanwood GmbH
readme: README.md
podspec: StanwoodDialog.podspec
github_url: https://github.com/stanwood/Stanwood_Dialog_iOS
min_acl: public
theme: fullwidth
